"""Host-only test of the server's penalty history (no GPU): Engine.generate on a fake model that keeps its own copy
of the sequence and checks, at every sampled call, the history the server passes against the C API's rule
(truss.h): truss_eval_sample counts the history as given, so it must end with the fed tokens; truss_spec_step_sampled
counts the history before `next` (the engine adds next and the drafts per verify row). penalty_last_n > 0: the last
n tokens of the sequence; -1: every token generated by the request.

  python3 tests/server/penalty_history_test.py
"""
import os
import sys
import threading
import types

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))
from server import app  # noqa: E402


class FakeModel:
    """Sampled calls emit 1000 + position; spec rounds accept two drafts (2000 + position ...)."""

    def __init__(self, spec, n_prompt, last_n):
        self.n_ctx, self.drafts = 10000, 3 if spec else 0
        self.n_prompt, self.last_n, self.seq, self.calls, self.bad = n_prompt, last_n, [], 0, 0

    @property
    def position(self):
        return len(self.seq)

    def reset(self):
        self.seq = []

    def checkpoint(self):
        pass

    def restore(self):
        return -1

    def check(self, sp):
        self.calls += 1
        want = self.seq[-self.last_n:] if self.last_n > 0 else self.seq[self.n_prompt:]
        got = [sp.history[i] for i in range(sp.n_history)]
        self.bad += got != want

    def eval_sample(self, tokens, sp):
        self.seq += list(tokens)
        self.check(sp)   # the fed tokens count
        return 1000 + self.position

    def spec_step_sampled(self, nxt, sp):
        self.check(sp)   # before nxt
        emitted = [nxt, 2000 + self.position, 2001 + self.position]
        self.seq += emitted
        return emitted, 1000 + self.position


def run(spec, last_n, n_prompt=100, n_gen=12):
    e = app.Engine.__new__(app.Engine)
    e.model = FakeModel(spec, n_prompt, last_n)
    e.chat = types.SimpleNamespace(tok=types.SimpleNamespace(decode=lambda ids, **k: "".join(f"<{i}>" for i in ids)))
    e.stop_ids, e.log_tag, e.log_path, e.dump_dir, e.cached, e.lock = set(), "test", None, None, [], threading.Lock()
    e.ck_tokens, e.keep_reasoning = [], -1
    e.log = lambda line: None
    out = [t for t, _, _ in e.generate(list(range(1, n_prompt + 1)), n_gen, 0.8, 0.95, 40, 7, [], 0.05,
                                       presence_penalty=1.5, penalty_last_n=last_n) if t is not None]
    ok = e.model.bad == 0 and e.model.calls > 1 and len(out) == n_gen and e.cached == e.model.seq
    print(f"spec {spec!s:5}, penalty_last_n {last_n:3d}: {e.model.calls} sampled calls, {e.model.bad} wrong histories, "
          f"{len(out)} tokens  {'PASS' if ok else 'FAIL'}")
    return ok


if __name__ == "__main__":
    ok = all([run(False, 64), run(False, -1), run(False, 8), run(True, 64), run(True, -1), run(True, 8)])
    print("PASS" if ok else "FAIL")
    sys.exit(0 if ok else 1)
